######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 28 05:58:05 2010
######################################################################

TEMPLATE = app
CONFIG += qt debug	
DEPENDPATH += .
INCLUDEPATH += .
QT+=widgets network xml
# Input
HEADERS += cacamap.h myderivedmap.h mainwidget.h servermanager.h
SOURCES += cacamap.cpp main.cpp myderivedmap.cpp mainwidget.cpp servermanager.cpp
